### ISSUE TITLE
OData Inheritance not supported

### ISSUE THREAD

**Issue by davidmoten** [microsoftgraph/msgraph-sdk-java#154]
A problem with the currently generated SDK is that  the generated entity and complex type classes do not mirror the single inheritance structure indicated in the odata metadata. As a consequence when I request a collection of Attachment (which may be an FileAttachment or an ItemAttachment or a ReferenceAttachment) I have to use its `@odata.type`to figure out what sort of Attachment it is and query again with the id to get back the full object (say FileAttachment).

So I have to make an extra call for every item in the collection to access its full data even though **the original collection JSON response already has that data**.

What I'd like to see happen is that the generated classes from odata subclasses of Attachment should inherit from Attachment so that when I iterate the collection I can use `instanceof` to process the Attachments without extra calls to the API.

Unfortunately, this issue and the typing problems touched upon in #25 make me think a rewrite of code generation is on the cards.

**Comment by deepak2016** [comment]
Thanks for reporting the issue @davidmoten we are looking into the issue of attachments.

**Comment by davidmoten** [comment]
@deepak2016 to be clear this is not an issue about attachments but about inheritance not being supported generally. Here is a list of subclasses (like FileAttachment, ItemAttachment) that suffer the same problem:

```
ActivityHistoryItem
AdministrativeUnit
AdministrativeUnit
AndroidCompliancePolicy
AndroidCompliancePolicy
AndroidCustomConfiguration
AndroidCustomConfiguration
AndroidGeneralDeviceConfiguration
AndroidGeneralDeviceConfiguration
AndroidLobApp
AndroidLobApp
AndroidManagedAppProtection
AndroidManagedAppProtection
AndroidManagedAppRegistration
AndroidManagedAppRegistration
AndroidStoreApp
AndroidStoreApp
AndroidWorkProfileCompliancePolicy
AndroidWorkProfileCompliancePolicy
AndroidWorkProfileCustomConfiguration
AndroidWorkProfileCustomConfiguration
AndroidWorkProfileGeneralDeviceConfiguration
AndroidWorkProfileGeneralDeviceConfiguration
AppleDeviceFeaturesConfigurationBase
AppleDeviceFeaturesConfigurationBase
ApplePushNotificationCertificate
Attachment
BaseItem
BaseItemVersion
CalendarGroup
Calendar
ColumnDefinition
ColumnLink
ContactFolder
Contact
Contact
ContentType
Contract
Contract
Conversation
ConversationThread
DefaultManagedAppProtection
DefaultManagedAppProtection
DetectedApp
DeviceAndAppManagementRoleAssignment
DeviceAndAppManagementRoleAssignment
DeviceAndAppManagementRoleDefinition
DeviceAndAppManagementRoleDefinition
DeviceAppManagement
DeviceCategory
DeviceComplianceActionItem
DeviceComplianceDeviceOverview
DeviceComplianceDeviceStatus
DeviceCompliancePolicyAssignment
DeviceCompliancePolicyDeviceStateSummary
DeviceCompliancePolicy
DeviceCompliancePolicySettingStateSummary
DeviceCompliancePolicyState
DeviceComplianceScheduledActionForRule
DeviceComplianceSettingState
DeviceComplianceUserOverview
DeviceComplianceUserStatus
DeviceConfigurationAssignment
DeviceConfigurationDeviceOverview
DeviceConfigurationDeviceStateSummary
DeviceConfigurationDeviceStatus
DeviceConfiguration
DeviceConfigurationState
DeviceConfigurationUserOverview
DeviceConfigurationUserStatus
DeviceEnrollmentConfiguration
DeviceEnrollmentLimitConfiguration
DeviceEnrollmentLimitConfiguration
DeviceEnrollmentPlatformRestrictionsConfiguration
DeviceEnrollmentPlatformRestrictionsConfiguration
DeviceEnrollmentWindowsHelloForBusinessConfiguration
DeviceEnrollmentWindowsHelloForBusinessConfiguration
DeviceInstallState
Device
Device
DeviceManagementExchangeConnector
DeviceManagement
DeviceManagementPartner
DeviceManagementTroubleshootingEvent
Directory
DirectoryObject
DirectoryRole
DirectoryRole
DirectoryRoleTemplate
DirectoryRoleTemplate
DomainDnsCnameRecord
DomainDnsCnameRecord
DomainDnsMxRecord
DomainDnsMxRecord
DomainDnsRecord
DomainDnsSrvRecord
DomainDnsSrvRecord
DomainDnsTxtRecord
DomainDnsTxtRecord
DomainDnsUnavailableRecord
DomainDnsUnavailableRecord
Domain
DriveItem
DriveItem
DriveItemVersion
DriveItemVersion
Drive
Drive
EBookInstallSummary
EditionUpgradeConfiguration
EditionUpgradeConfiguration
EducationClass
EducationOrganization
EducationRoot
EducationSchool
EducationSchool
EducationUser
EnrollmentConfigurationAssignment
EnrollmentTroubleshootingEvent
EnrollmentTroubleshootingEvent
Event
Event
EventMessage
EventMessage
Extension
FieldValueSet
FileAttachment
FileAttachment
Group
Group
GroupLifecyclePolicy
GroupSetting
GroupSettingTemplate
GroupSettingTemplate
InferenceClassification
InferenceClassificationOverride
Invitation
IosCertificateProfile
IosCertificateProfile
IosCompliancePolicy
IosCompliancePolicy
IosCustomConfiguration
IosCustomConfiguration
IosDeviceFeaturesConfiguration
IosDeviceFeaturesConfiguration
IosGeneralDeviceConfiguration
IosGeneralDeviceConfiguration
IosLobApp
IosLobApp
IosManagedAppProtection
IosManagedAppProtection
IosManagedAppRegistration
IosManagedAppRegistration
IosMobileAppConfiguration
IosMobileAppConfiguration
IosStoreApp
IosStoreApp
IosUpdateConfiguration
IosUpdateConfiguration
IosUpdateDeviceStatus
IosVppApp
IosVppApp
IosVppEBookAssignment
IosVppEBookAssignment
IosVppEBook
IosVppEBook
ItemAttachment
ItemAttachment
LicenseDetails
ListItem
ListItem
ListItemVersion
ListItemVersion
List
List
LocalizedNotificationMessage
MacOSCompliancePolicy
MacOSCompliancePolicy
MacOSCustomConfiguration
MacOSCustomConfiguration
MacOSDeviceFeaturesConfiguration
MacOSDeviceFeaturesConfiguration
MacOSGeneralDeviceConfiguration
MacOSGeneralDeviceConfiguration
MacOSOfficeSuiteApp
MacOSOfficeSuiteApp
MailFolder
ManagedAndroidLobApp
ManagedAndroidLobApp
ManagedAndroidStoreApp
ManagedAndroidStoreApp
ManagedAppConfiguration
ManagedAppConfiguration
ManagedApp
ManagedApp
ManagedAppOperation
ManagedAppPolicyDeploymentSummary
ManagedAppPolicy
ManagedAppProtection
ManagedAppProtection
ManagedAppRegistration
ManagedAppStatus
ManagedAppStatusRaw
ManagedAppStatusRaw
ManagedDevice
ManagedDeviceMobileAppConfigurationAssignment
ManagedDeviceMobileAppConfigurationDeviceStatus
ManagedDeviceMobileAppConfigurationDeviceSummary
ManagedDeviceMobileAppConfiguration
ManagedDeviceMobileAppConfigurationUserStatus
ManagedDeviceMobileAppConfigurationUserSummary
ManagedDeviceOverview
ManagedEBookAssignment
ManagedEBook
ManagedIOSLobApp
ManagedIOSLobApp
ManagedIOSStoreApp
ManagedIOSStoreApp
ManagedMobileApp
ManagedMobileLobApp
ManagedMobileLobApp
MdmWindowsInformationProtectionPolicy
MdmWindowsInformationProtectionPolicy
Message
Message
MessageRule
MicrosoftStoreForBusinessApp
MicrosoftStoreForBusinessApp
MobileAppAssignment
MobileAppCategory
MobileAppContentFile
MobileAppContent
MobileApp
MobileLobApp
MobileLobApp
MobileThreatDefenseConnector
MultiValueLegacyExtendedProperty
Notebook
Notebook
NotificationMessageTemplate
OnenoteEntityBaseModel
OnenoteEntityHierarchyModel
OnenoteEntityHierarchyModel
OnenoteEntitySchemaObjectModel
OnenoteEntitySchemaObjectModel
Onenote
OnenoteOperation
OnenoteOperation
OnenotePage
OnenotePage
OnenoteResource
OnenoteResource
OnenoteSection
OnenoteSection
OnPremisesConditionalAccessSettings
OpenTypeExtension
OpenTypeExtension
Operation
Organization
Organization
OutlookCategory
OutlookItem
OutlookUser
Permission
Person
PlannerAssignedToTaskBoardTaskFormat
PlannerBucket
PlannerBucketTaskBoardTaskFormat
PlannerGroup
Planner
PlannerPlanDetails
PlannerPlan
PlannerProgressTaskBoardTaskFormat
PlannerTaskDetails
PlannerTask
PlannerUser
Post
Post
ProfilePhoto
ReferenceAttachment
ReferenceAttachment
RemoteAssistancePartner
ReportRoot
request/EntityRequest
ResourceOperation
RoleAssignment
RoleDefinition
SchemaExtension
SectionGroup
SectionGroup
SettingStateDeviceSummary
SharedDriveItem
SharedDriveItem
SharedPCConfiguration
SharedPCConfiguration
SingleValueLegacyExtendedProperty
Site
Site
SoftwareUpdateStatusSummary
SubscribedSku
Subscription
TargetedManagedAppConfiguration
TargetedManagedAppConfiguration
TargetedManagedAppPolicyAssignment
TargetedManagedAppProtection
TargetedManagedAppProtection
TelecomExpenseManagementPartner
TermsAndConditionsAcceptanceStatus
TermsAndConditionsAssignment
TermsAndConditions
ThumbnailSet
UserActivity
UserInstallStateSummary
User
User
VppToken
WebApp
WebApp
Windows10CompliancePolicy
Windows10CompliancePolicy
Windows10CustomConfiguration
Windows10CustomConfiguration
Windows10EndpointProtectionConfiguration
Windows10EndpointProtectionConfiguration
Windows10EnterpriseModernAppManagementConfiguration
Windows10EnterpriseModernAppManagementConfiguration
Windows10GeneralConfiguration
Windows10GeneralConfiguration
Windows10MobileCompliancePolicy
Windows10MobileCompliancePolicy
Windows10SecureAssessmentConfiguration
Windows10SecureAssessmentConfiguration
Windows10TeamGeneralConfiguration
Windows10TeamGeneralConfiguration
Windows81CompliancePolicy
Windows81CompliancePolicy
Windows81GeneralConfiguration
Windows81GeneralConfiguration
WindowsDefenderAdvancedThreatProtectionConfiguration
WindowsDefenderAdvancedThreatProtectionConfiguration
WindowsInformationProtectionAppLearningSummary
WindowsInformationProtectionAppLockerFile
WindowsInformationProtection
WindowsInformationProtection
WindowsInformationProtectionNetworkLearningSummary
WindowsInformationProtectionPolicy
WindowsInformationProtectionPolicy
WindowsMobileMSI
WindowsMobileMSI
WindowsPhone81CompliancePolicy
WindowsPhone81CompliancePolicy
WindowsPhone81CustomConfiguration
WindowsPhone81CustomConfiguration
WindowsPhone81GeneralConfiguration
WindowsPhone81GeneralConfiguration
WindowsUniversalAppX
WindowsUniversalAppX
WindowsUpdateForBusinessConfiguration
WindowsUpdateForBusinessConfiguration
WorkbookApplication
WorkbookChartAreaFormat
WorkbookChartAxes
WorkbookChartAxisFormat
WorkbookChartAxis
WorkbookChartAxisTitleFormat
WorkbookChartAxisTitle
WorkbookChartDataLabelFormat
WorkbookChartDataLabels
WorkbookChartFill
WorkbookChartFont
WorkbookChartGridlinesFormat
WorkbookChartGridlines
WorkbookChart
WorkbookChartLegendFormat
WorkbookChartLegend
WorkbookChartLineFormat
WorkbookChartPointFormat
WorkbookChartPoint
WorkbookChartSeriesFormat
WorkbookChartSeries
WorkbookChartTitleFormat
WorkbookChartTitle
WorkbookFilter
WorkbookFormatProtection
WorkbookFunctionResult
WorkbookFunctions
Workbook
WorkbookNamedItem
WorkbookPivotTable
WorkbookRangeBorder
WorkbookRangeFill
WorkbookRangeFont
WorkbookRangeFormat
WorkbookRange
WorkbookRangeSort
WorkbookRangeView
WorkbookTableColumn
WorkbookTable
WorkbookTableRow
WorkbookTableSort
WorkbookWorksheet
WorkbookWorksheetProtection
```

**Comment by davidmoten** [comment]
I've fixed the list

**Comment by darrelmiller** [comment]
We have reviewed model classes and the examples we looked at derived from the same base classes as are defined in the OData metadata.  We believe they were fixed in this commit https://github.com/microsoftgraph/msgraph-sdk-java/commit/2340ac50723e570575f0a2535c2c199429fc2552

**Comment by ProRoman** [comment]
Hi 
Still have the same issue 
Exception in thread "main" java.lang.ClassCastException: com.microsoft.graph.models.extensions.Attachment cannot be cast to com.microsoft.graph.models.extensions.FileAttachment. sdk version 2.5. 
Object type is Attachment but should be FileAttachment

![1](https://user-images.githubusercontent.com/12507631/103353463-fda84280-4ab9-11eb-8987-0afb0117caa6.png)

`IAttachmentCollectionPage attachments = graphClient.users(id).mailFolders(inbox).messages(id).attachments().buildRequest() .get();`

`attachments.getCurrentPage().stream().forEach(
                attachment ->
                {
                    if (attachment.oDataType.equals("#microsoft.graph.fileAttachment")) {`
